plugin:
    name: 'shohabbos.uzcard::lang.plugin.name'
    description: 'shohabbos.uzcard::lang.plugin.description'
    author: Shohabbos
    icon: oc-icon-puzzle-piece
    homepage: 'https://itmaker.uz'
permissions:
    manage_uzcard_transactions:
        tab: 'shohabbos.uzcard::lang.plugin.name'
        label: 'Manage transactions'
    manage_uzcard_settings:
        tab: 'shohabbos.uzcard::lang.plugin.name'
        label: 'Manage settings'
